import { darkThemeClass, lightThemeClass } from "@/components/theme";
import "./globals.css";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import { sx } from "@/components/styled";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const bodyClass = sx({
  color: "text.primary",
  backgroundColor: "background.default",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const mode = cookies().get("mode");
  return (
    <html
      lang="en"
      className={mode?.value === "dark" ? darkThemeClass : lightThemeClass}
    >
      <body className={`${inter.className} ${bodyClass}`}>{children}</body>
    </html>
  );
}
